//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.SoapWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRaces", ReplyAction="*")]
        WebClient.SoapWebService.ShowRacesResponse ShowRaces(WebClient.SoapWebService.ShowRacesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRaces", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.SoapWebService.ShowRacesResponse> ShowRacesAsync(WebClient.SoapWebService.ShowRacesRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTickets", ReplyAction="*")]
        WebClient.SoapWebService.CheckTicketsResponse CheckTickets(WebClient.SoapWebService.CheckTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.SoapWebService.CheckTicketsResponse> CheckTicketsAsync(WebClient.SoapWebService.CheckTicketsRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyTicket", ReplyAction="*")]
        WebClient.SoapWebService.BuyTicketResponse BuyTicket(WebClient.SoapWebService.BuyTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.SoapWebService.BuyTicketResponse> BuyTicketAsync(WebClient.SoapWebService.BuyTicketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRacesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRaces", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.ShowRacesRequestBody Body;
        
        public ShowRacesRequest() {
        }
        
        public ShowRacesRequest(WebClient.SoapWebService.ShowRacesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowRacesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinition;
        
        public ShowRacesRequestBody() {
        }
        
        public ShowRacesRequestBody(string source, string destinition) {
            this.source = source;
            this.destinition = destinition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRacesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRacesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.ShowRacesResponseBody Body;
        
        public ShowRacesResponse() {
        }
        
        public ShowRacesResponse(WebClient.SoapWebService.ShowRacesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowRacesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowRacesResult;
        
        public ShowRacesResponseBody() {
        }
        
        public ShowRacesResponseBody(string ShowRacesResult) {
            this.ShowRacesResult = ShowRacesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTickets", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.CheckTicketsRequestBody Body;
        
        public CheckTicketsRequest() {
        }
        
        public CheckTicketsRequest(WebClient.SoapWebService.CheckTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime time;
        
        public CheckTicketsRequestBody() {
        }
        
        public CheckTicketsRequestBody(string source, string destinition, System.DateTime time) {
            this.source = source;
            this.destinition = destinition;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.CheckTicketsResponseBody Body;
        
        public CheckTicketsResponse() {
        }
        
        public CheckTicketsResponse(WebClient.SoapWebService.CheckTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTicketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckTicketsResult;
        
        public CheckTicketsResponseBody() {
        }
        
        public CheckTicketsResponseBody(string CheckTicketsResult) {
            this.CheckTicketsResult = CheckTicketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyTicket", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.BuyTicketRequestBody Body;
        
        public BuyTicketRequest() {
        }
        
        public BuyTicketRequest(WebClient.SoapWebService.BuyTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime time;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int seat;
        
        public BuyTicketRequestBody() {
        }
        
        public BuyTicketRequestBody(string source, string destinition, System.DateTime time, int seat) {
            this.source = source;
            this.destinition = destinition;
            this.time = time;
            this.seat = seat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyTicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.SoapWebService.BuyTicketResponseBody Body;
        
        public BuyTicketResponse() {
        }
        
        public BuyTicketResponse(WebClient.SoapWebService.BuyTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuyTicketResult;
        
        public BuyTicketResponseBody() {
        }
        
        public BuyTicketResponseBody(string BuyTicketResult) {
            this.BuyTicketResult = BuyTicketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebClient.SoapWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebClient.SoapWebService.WebServiceSoap>, WebClient.SoapWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.SoapWebService.ShowRacesResponse WebClient.SoapWebService.WebServiceSoap.ShowRaces(WebClient.SoapWebService.ShowRacesRequest request) {
            return base.Channel.ShowRaces(request);
        }
        
        public string ShowRaces(string source, string destinition) {
            WebClient.SoapWebService.ShowRacesRequest inValue = new WebClient.SoapWebService.ShowRacesRequest();
            inValue.Body = new WebClient.SoapWebService.ShowRacesRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            WebClient.SoapWebService.ShowRacesResponse retVal = ((WebClient.SoapWebService.WebServiceSoap)(this)).ShowRaces(inValue);
            return retVal.Body.ShowRacesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.SoapWebService.ShowRacesResponse> WebClient.SoapWebService.WebServiceSoap.ShowRacesAsync(WebClient.SoapWebService.ShowRacesRequest request) {
            return base.Channel.ShowRacesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.SoapWebService.ShowRacesResponse> ShowRacesAsync(string source, string destinition) {
            WebClient.SoapWebService.ShowRacesRequest inValue = new WebClient.SoapWebService.ShowRacesRequest();
            inValue.Body = new WebClient.SoapWebService.ShowRacesRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            return ((WebClient.SoapWebService.WebServiceSoap)(this)).ShowRacesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.SoapWebService.CheckTicketsResponse WebClient.SoapWebService.WebServiceSoap.CheckTickets(WebClient.SoapWebService.CheckTicketsRequest request) {
            return base.Channel.CheckTickets(request);
        }
        
        public string CheckTickets(string source, string destinition, System.DateTime time) {
            WebClient.SoapWebService.CheckTicketsRequest inValue = new WebClient.SoapWebService.CheckTicketsRequest();
            inValue.Body = new WebClient.SoapWebService.CheckTicketsRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            inValue.Body.time = time;
            WebClient.SoapWebService.CheckTicketsResponse retVal = ((WebClient.SoapWebService.WebServiceSoap)(this)).CheckTickets(inValue);
            return retVal.Body.CheckTicketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.SoapWebService.CheckTicketsResponse> WebClient.SoapWebService.WebServiceSoap.CheckTicketsAsync(WebClient.SoapWebService.CheckTicketsRequest request) {
            return base.Channel.CheckTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.SoapWebService.CheckTicketsResponse> CheckTicketsAsync(string source, string destinition, System.DateTime time) {
            WebClient.SoapWebService.CheckTicketsRequest inValue = new WebClient.SoapWebService.CheckTicketsRequest();
            inValue.Body = new WebClient.SoapWebService.CheckTicketsRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            inValue.Body.time = time;
            return ((WebClient.SoapWebService.WebServiceSoap)(this)).CheckTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.SoapWebService.BuyTicketResponse WebClient.SoapWebService.WebServiceSoap.BuyTicket(WebClient.SoapWebService.BuyTicketRequest request) {
            return base.Channel.BuyTicket(request);
        }
        
        public string BuyTicket(string source, string destinition, System.DateTime time, int seat) {
            WebClient.SoapWebService.BuyTicketRequest inValue = new WebClient.SoapWebService.BuyTicketRequest();
            inValue.Body = new WebClient.SoapWebService.BuyTicketRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            inValue.Body.time = time;
            inValue.Body.seat = seat;
            WebClient.SoapWebService.BuyTicketResponse retVal = ((WebClient.SoapWebService.WebServiceSoap)(this)).BuyTicket(inValue);
            return retVal.Body.BuyTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.SoapWebService.BuyTicketResponse> WebClient.SoapWebService.WebServiceSoap.BuyTicketAsync(WebClient.SoapWebService.BuyTicketRequest request) {
            return base.Channel.BuyTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.SoapWebService.BuyTicketResponse> BuyTicketAsync(string source, string destinition, System.DateTime time, int seat) {
            WebClient.SoapWebService.BuyTicketRequest inValue = new WebClient.SoapWebService.BuyTicketRequest();
            inValue.Body = new WebClient.SoapWebService.BuyTicketRequestBody();
            inValue.Body.source = source;
            inValue.Body.destinition = destinition;
            inValue.Body.time = time;
            inValue.Body.seat = seat;
            return ((WebClient.SoapWebService.WebServiceSoap)(this)).BuyTicketAsync(inValue);
        }
    }
}
